default_config:

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  name: Security Hub
  allowlist_external_dirs:
    - /config/www/snapshots

mqtt:
  broker: !secret mqtt_broker_ip
  port: 1883
  username: firstplace
  password: firstplacepassword

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.2.246/stream
    still_image_url: http://192.168.2.246/snapshot.jpg
    name: Cam01

binary_sensor:
  - platform: mqtt
    name: "Camera Motion"
    unique_id: camera_motion_sensor_01
    state_topic: "camera/motion"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: motion

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
